import type { Project, ProjectCategory, ProjectCategoryInfo } from "@/types";

export const PROJECT_CATEGORIES: ProjectCategoryInfo[] = [
  { value: "google-ads", label: "Google Ads & PPC", icon: "BarChart3", description: "Pay-per-click campaigns that deliver qualified leads" },
  { value: "seo", label: "SEO & Online Presence", icon: "Search", description: "Dominate local search results and online visibility" },
  { value: "website-design", label: "Website Design", icon: "Globe", description: "Conversion-optimized websites built for home services" },
  { value: "ai-receptionist", label: "AI Receptionist", icon: "PhoneCall", description: "Never miss a lead with AI-powered call handling" },
  { value: "full-service", label: "Full-Service", icon: "Bot", description: "Complete digital marketing transformation" },
];

export const PROJECTS: Project[] = [
  // ── Google Ads & PPC (12 projects) ──
  {
    title: "From 12 to 67 Leads Per Month with Google Ads",
    slug: "johnson-plumbing-google-ads",
    client: "Johnson's Plumbing Co.",
    industry: "Residential Plumbing",
    category: "google-ads",
    featured: true,
    summary: "A struggling family plumbing business transformed into the busiest shop in town with laser-targeted Google Ads campaigns.",
    challenge: "Johnson's Plumbing was spending $2,000/month on generic Google Ads managed by a general marketing agency. They were getting clicks but barely any phone calls. Their cost per lead was over $180 and most inquiries were for services they didn't even offer.",
    solution: "We rebuilt their entire Google Ads strategy from scratch with plumbing-specific keyword targeting, negative keyword lists, and geo-fenced campaigns around their service area. We created dedicated landing pages for each service line with click-to-call CTAs and built a call tracking system to attribute every lead.",
    results: "Within 60 days, Johnson's Plumbing went from 12 leads per month to 67. Their cost per lead dropped from $180 to $34, and their monthly revenue increased by $45,000. They hired two additional plumbers to handle the demand.",
    metrics: [
      { label: "Leads Per Month", before: "12", after: "67", suffix: "/mo", improvement: "+458%" },
      { label: "Cost Per Lead", before: "$180", after: "$34", improvement: "-81%" },
      { label: "Monthly Revenue", before: "$28K", after: "$73K", improvement: "+161%" },
      { label: "Conversion Rate", before: "2.1%", after: "11.8%", suffix: "%", improvement: "+462%" },
    ],
    testimonial: { quote: "We went from barely surviving to having to hire two new plumbers in less than 90 days. LexumSoft didn't just fix our ads — they transformed our entire business.", name: "Mike Johnson", role: "Owner" },
    services: ["Google Ads", "Landing Pages", "Call Tracking", "Conversion Optimization"],
    timeline: "60 days",
    heroStat: "458% More Leads",
  },
  {
    title: "HVAC Company Cuts Cost Per Lead by 63%",
    slug: "arctic-comfort-hvac-ppc",
    client: "Arctic Comfort HVAC",
    industry: "Residential HVAC",
    category: "google-ads",
    featured: false,
    summary: "An HVAC company was bleeding money on inefficient ad campaigns until we rebuilt their PPC strategy from the ground up.",
    challenge: "Arctic Comfort HVAC was spending $5,000/month on Google Ads with a cost per lead of $210. Their campaigns were targeting broad keywords that attracted tire-kickers and out-of-area clicks. They were considering cutting their ad budget entirely.",
    solution: "We implemented hyper-local targeting with service-specific ad groups for AC repair, furnace installation, and maintenance plans. We added call-only campaigns for mobile users and set up automated bid strategies optimized for phone calls rather than clicks.",
    results: "Their cost per lead dropped from $210 to $78 while lead volume tripled. The quality of leads also improved dramatically — their close rate went from 15% to 38%. Arctic Comfort generated over $120K in new revenue in the first quarter.",
    metrics: [
      { label: "Cost Per Lead", before: "$210", after: "$78", improvement: "-63%" },
      { label: "Monthly Leads", before: "24", after: "72", suffix: "/mo", improvement: "+200%" },
      { label: "Close Rate", before: "15%", after: "38%", suffix: "%", improvement: "+153%" },
      { label: "Quarterly Revenue", before: "$45K", after: "$120K", improvement: "+167%" },
    ],
    testimonial: { quote: "We were about to cut our entire ad budget before LexumSoft stepped in. Now Google Ads is our number one source of new business. The ROI is incredible.", name: "Tom Richards", role: "Owner" },
    services: ["Google Ads", "Call-Only Campaigns", "Bid Optimization", "Call Tracking"],
    timeline: "90 days",
    heroStat: "63% Lower CPA",
  },
  {
    title: "Emergency Plumber Doubles Call Volume Overnight",
    slug: "quickdrain-emergency-ppc",
    client: "QuickDrain Solutions",
    industry: "Emergency Plumbing",
    category: "google-ads",
    featured: false,
    summary: "An emergency plumbing service needed more after-hours calls and we delivered with targeted campaigns that run when competitors sleep.",
    challenge: "QuickDrain Solutions specialized in 24/7 emergency plumbing but their ads only ran during business hours. They were losing thousands in potential revenue every night to competitors who happened to show up in late-night search results.",
    solution: "We created time-based campaign strategies with higher bids during evenings, weekends, and holidays when emergency calls spike. We built urgency-focused landing pages with prominent click-to-call buttons and real-time availability messaging.",
    results: "After-hours call volume doubled within the first month. QuickDrain went from averaging 8 emergency calls per week to 22. Their average job value for emergency work was $650, translating to an extra $9,100 per week in revenue.",
    metrics: [
      { label: "Weekly Emergency Calls", before: "8", after: "22", suffix: "/wk", improvement: "+175%" },
      { label: "After-Hours Leads", before: "3", after: "14", suffix: "/wk", improvement: "+367%" },
      { label: "Weekly Revenue", before: "$5.2K", after: "$14.3K", improvement: "+175%" },
      { label: "Ad Spend ROI", before: "2.1x", after: "8.4x", improvement: "+300%" },
    ],
    testimonial: { quote: "Our phone rings at 2 AM now and that's a great problem to have. Every one of those calls is a $500+ emergency job. LexumSoft understood exactly what we needed.", name: "Carlos Mendez", role: "Owner" },
    services: ["Google Ads", "Time-Based Bidding", "Emergency Landing Pages", "Call Tracking"],
    timeline: "30 days",
    heroStat: "175% More Calls",
  },
  {
    title: "HVAC Installer Fills Calendar with Google Ads",
    slug: "all-seasons-heating-ads",
    client: "All Seasons Heating & Air",
    industry: "Residential HVAC",
    category: "google-ads",
    featured: false,
    summary: "A heating and air company went from empty install calendar to fully booked three weeks out using targeted Google Ads campaigns.",
    challenge: "All Seasons had a great reputation for installations but relied entirely on word-of-mouth referrals. When a slow season hit, they had technicians sitting idle for weeks. They needed a consistent pipeline of installation leads.",
    solution: "We launched targeted campaigns for furnace and AC installation keywords in their service area. We created comparison landing pages showcasing their pricing, warranty, and 5-star reviews against competitors. We also set up retargeting to follow up with visitors who didn't convert.",
    results: "Within 45 days, All Seasons had a fully booked installation calendar extending three weeks out. Their install lead volume went from 5 per month to 28, and they added a second installation crew to meet demand.",
    metrics: [
      { label: "Install Leads/Month", before: "5", after: "28", suffix: "/mo", improvement: "+460%" },
      { label: "Calendar Utilization", before: "40%", after: "95%", suffix: "%", improvement: "+138%" },
      { label: "Cost Per Install Lead", before: "$340", after: "$95", improvement: "-72%" },
      { label: "Monthly Install Revenue", before: "$18K", after: "$82K", improvement: "+356%" },
    ],
    testimonial: { quote: "We went from having guys on the bench to being booked solid three weeks out. That's never happened in 15 years of business. These guys know HVAC marketing.", name: "Gary Patterson", role: "Owner" },
    services: ["Google Ads", "Retargeting", "Landing Pages", "Competitor Analysis"],
    timeline: "45 days",
    heroStat: "460% More Installs",
  },
  {
    title: "Commercial Plumber Wins $2M in New Contracts",
    slug: "metro-plumbing-commercial-ads",
    client: "Metro Plumbing Services",
    industry: "Commercial Plumbing",
    category: "google-ads",
    featured: false,
    summary: "A commercial plumbing company broke into the enterprise market with targeted B2B ad campaigns and lead nurturing.",
    challenge: "Metro Plumbing wanted to land larger commercial contracts but their marketing only attracted residential customers. They had no presence in B2B search results and no strategy for reaching property managers and general contractors.",
    solution: "We built separate B2B campaigns targeting commercial plumbing keywords with industry-specific ad copy. We created professional landing pages with case studies, certifications, and a quote request form. LinkedIn retargeting helped nurture decision-makers.",
    results: "Metro Plumbing secured 14 new commercial contracts in 6 months, including two property management companies worth $200K+ annually each. Their commercial revenue went from $150K to over $2M annually.",
    metrics: [
      { label: "Commercial Leads/Month", before: "2", after: "18", suffix: "/mo", improvement: "+800%" },
      { label: "New Contracts (6 mo)", before: "1", after: "14", improvement: "+1300%" },
      { label: "Annual Commercial Revenue", before: "$150K", after: "$2M", improvement: "+1233%" },
      { label: "Average Contract Value", before: "$12K", after: "$45K", improvement: "+275%" },
    ],
    testimonial: { quote: "LexumSoft helped us break into the commercial market. We went from chasing small residential jobs to landing six-figure contracts with property management firms.", name: "Daniel Hayes", role: "VP of Operations" },
    services: ["Google Ads", "LinkedIn Ads", "B2B Landing Pages", "Lead Nurturing"],
    timeline: "6 months",
    heroStat: "$2M in Contracts",
  },
  {
    title: "HVAC Company Dominates Local Services Ads",
    slug: "precision-climate-lsa",
    client: "Precision Climate Control",
    industry: "Commercial HVAC",
    category: "google-ads",
    featured: false,
    summary: "An HVAC company leveraged Google Local Services Ads to become the top-ranked provider in their metro area.",
    challenge: "Precision Climate was invisible in Google's Local Services Ads section. Their competitors were getting the Google Guaranteed badge and capturing premium leads while Precision relied on outdated Yellow Pages ads and declining referrals.",
    solution: "We managed their entire LSA setup — background checks, license verification, review generation, and profile optimization. We implemented a review request automation system and optimized their service categories for maximum visibility.",
    results: "Precision Climate earned the Google Guaranteed badge and rose to the #1 position in Local Services Ads for their area. They now receive 40+ LSA leads per month at an average cost of $25 per lead.",
    metrics: [
      { label: "LSA Leads/Month", before: "0", after: "42", suffix: "/mo", improvement: "New Channel" },
      { label: "Google Reviews", before: "23", after: "187", improvement: "+713%" },
      { label: "Cost Per LSA Lead", before: "N/A", after: "$25", improvement: "New" },
      { label: "Monthly Revenue from LSA", before: "$0", after: "$38K", improvement: "New" },
    ],
    testimonial: { quote: "We had no idea Local Services Ads even existed. Now it's our top lead source. The Google Guaranteed badge gives customers instant trust in our company.", name: "Frank Morrison", role: "General Manager" },
    services: ["Local Services Ads", "Review Generation", "Profile Optimization", "Call Tracking"],
    timeline: "60 days",
    heroStat: "#1 in Local Ads",
  },
  {
    title: "Residential Plumber 5x Return on Ad Spend",
    slug: "redpipe-plumbing-roas",
    client: "RedPipe Plumbing",
    industry: "Residential Plumbing",
    category: "google-ads",
    featured: false,
    summary: "A plumbing company turned every $1 of ad spend into $5 of revenue with strategically optimized PPC campaigns.",
    challenge: "RedPipe Plumbing was spending $3,000/month on ads but barely breaking even. Their campaigns were poorly structured with one ad group targeting dozens of unrelated keywords. They had no conversion tracking and no idea which ads worked.",
    solution: "We restructured their account into tightly themed ad groups with specific keywords for each service. We installed conversion tracking, set up automated bidding for maximum conversions, and wrote compelling ad copy with strong calls to action.",
    results: "RedPipe's return on ad spend jumped from 1.2x to 5.3x. Their monthly revenue from paid ads went from $3,600 to $15,900 while keeping the same $3,000 budget. They now reinvest profits to scale further.",
    metrics: [
      { label: "Return on Ad Spend", before: "1.2x", after: "5.3x", improvement: "+342%" },
      { label: "Revenue from Ads", before: "$3.6K", after: "$15.9K", suffix: "/mo", improvement: "+342%" },
      { label: "Quality Score (Avg)", before: "4.2", after: "8.7", improvement: "+107%" },
      { label: "Click-Through Rate", before: "1.8%", after: "7.2%", suffix: "%", improvement: "+300%" },
    ],
    testimonial: { quote: "Same budget, completely different results. LexumSoft turned our money pit into a money machine. Every dollar we spend now comes back five-fold.", name: "Robert Kim", role: "Owner" },
    services: ["Google Ads", "Conversion Tracking", "A/B Testing", "Bid Management"],
    timeline: "45 days",
    heroStat: "5.3x ROAS",
  },
  {
    title: "HVAC Company Conquers Seasonal Slumps",
    slug: "summit-air-seasonal-ads",
    client: "Summit Air Solutions",
    industry: "Residential HVAC",
    category: "google-ads",
    featured: false,
    summary: "An HVAC company eliminated feast-or-famine revenue cycles with year-round Google Ads strategies targeting seasonal demand.",
    challenge: "Summit Air had great summers but dead winters. Their revenue dropped 70% between October and March every year. They had no marketing strategy for their shoulder seasons and relied on emergency repairs to survive the off-months.",
    solution: "We created seasonal campaign calendars — furnace tune-up ads in fall, heating repair in winter, AC maintenance in spring, and installation pushes in summer. Each season had unique landing pages, ad copy, and promotional offers.",
    results: "Summit Air's winter revenue tripled and their overall annual revenue grew by 65%. They eliminated the feast-or-famine cycle entirely, with consistent lead flow across all 12 months for the first time in company history.",
    metrics: [
      { label: "Winter Revenue", before: "$12K/mo", after: "$38K/mo", improvement: "+217%" },
      { label: "Annual Revenue", before: "$320K", after: "$528K", improvement: "+65%" },
      { label: "Year-Round Lead Flow", before: "Seasonal", after: "Consistent", improvement: "Stabilized" },
      { label: "Maintenance Plan Signups", before: "8/mo", after: "34/mo", suffix: "/mo", improvement: "+325%" },
    ],
    testimonial: { quote: "For the first time in 20 years, I'm not worried about making payroll in January. LexumSoft figured out how to keep our phones ringing all year.", name: "Bill Crawford", role: "Owner" },
    services: ["Google Ads", "Seasonal Campaigns", "Landing Pages", "Maintenance Marketing"],
    timeline: "6 months",
    heroStat: "65% Revenue Growth",
  },
  {
    title: "Drain Cleaning Company Triples Monthly Bookings",
    slug: "clearflow-drain-ads",
    client: "ClearFlow Plumbing",
    industry: "Drain Services",
    category: "google-ads",
    featured: false,
    summary: "A drain cleaning specialist went from 20 bookings per month to 65 with targeted campaigns and optimized landing pages.",
    challenge: "ClearFlow specialized in drain cleaning and sewer repair but their generic plumbing ads attracted callers looking for fixture installations and water heater work they didn't offer. Most of their ad spend was wasted on irrelevant leads.",
    solution: "We built drain-specific campaigns targeting exact keywords like drain cleaning, sewer line repair, and hydro jetting. Extensive negative keyword lists filtered out irrelevant searches. Service-specific landing pages with before/after drain photos drove conversions.",
    results: "ClearFlow's monthly bookings jumped from 20 to 65 while their cost per booking dropped by 55%. Every lead was now specifically looking for drain services, which dramatically improved their close rate.",
    metrics: [
      { label: "Monthly Bookings", before: "20", after: "65", suffix: "/mo", improvement: "+225%" },
      { label: "Cost Per Booking", before: "$145", after: "$65", improvement: "-55%" },
      { label: "Lead Relevance Rate", before: "35%", after: "92%", suffix: "%", improvement: "+163%" },
      { label: "Monthly Revenue", before: "$7K", after: "$22.7K", improvement: "+224%" },
    ],
    testimonial: { quote: "Every call we get now is actually someone who needs drain work. We stopped wasting time on leads that didn't match our services. Our guys are busy every single day.", name: "Pete Alvarez", role: "Operations Manager" },
    services: ["Google Ads", "Negative Keywords", "Service Landing Pages", "Call Tracking"],
    timeline: "30 days",
    heroStat: "225% More Bookings",
  },
  {
    title: "Desert HVAC Company Dominates Summer Rush",
    slug: "desert-cool-summer-ads",
    client: "Desert Cool HVAC",
    industry: "Residential HVAC",
    category: "google-ads",
    featured: false,
    summary: "A Phoenix HVAC company captured maximum market share during the critical summer AC season with aggressive PPC strategies.",
    challenge: "Desert Cool HVAC operated in one of the most competitive HVAC markets in the country. During summer, AC repair costs per click exceeded $45 and they were getting outbid by larger companies with bigger budgets.",
    solution: "We implemented smart bidding strategies to win auctions at lower costs. We created urgency-driven ad copy for the extreme heat season and built a pre-season campaign to lock in maintenance customers before the rush. Ad scheduling maximized budget during peak search hours.",
    results: "Desert Cool captured 23% of their local market's paid search traffic during summer, up from 4%. They booked 340 service calls in June alone — a company record — while spending 20% less than the previous summer.",
    metrics: [
      { label: "Market Share (Paid)", before: "4%", after: "23%", suffix: "%", improvement: "+475%" },
      { label: "June Service Calls", before: "95", after: "340", improvement: "+258%" },
      { label: "Summer Ad Spend", before: "$18K", after: "$14.4K", improvement: "-20%" },
      { label: "Summer Revenue", before: "$85K", after: "$272K", improvement: "+220%" },
    ],
    testimonial: { quote: "We used to dread competing with the big guys during summer. Now we outperform companies three times our size. The smart bidding strategy LexumSoft built is unbeatable.", name: "Ray Torres", role: "Owner" },
    services: ["Google Ads", "Smart Bidding", "Seasonal Strategy", "Competitor Analysis"],
    timeline: "90 days",
    heroStat: "258% More Calls",
  },
  {
    title: "Family Plumber Beats National Chains Online",
    slug: "patriot-plumbing-ads",
    client: "Patriot Plumbing",
    industry: "Residential Plumbing",
    category: "google-ads",
    featured: false,
    summary: "A family-owned plumbing company outperformed Roto-Rooter and other national chains in their local Google Ads results.",
    challenge: "Patriot Plumbing was a third-generation family business competing against national chains with massive ad budgets. They were consistently pushed off the first page of Google Ads results and losing market share to corporate competitors.",
    solution: "We leveraged the family-owned advantage — trust signals, local roots, and personal service — in ad copy. We targeted long-tail keywords the national chains ignored, and created landing pages emphasizing local testimonials, same-day service, and veteran-owned business credentials.",
    results: "Patriot Plumbing now outranks national chains in their local Google Ads for 78% of their target keywords. Their lead volume increased by 190% and they've expanded to serve two additional counties.",
    metrics: [
      { label: "Keyword Visibility", before: "22%", after: "78%", suffix: "%", improvement: "+255%" },
      { label: "Monthly Leads", before: "18", after: "52", suffix: "/mo", improvement: "+189%" },
      { label: "Cost Per Lead", before: "$155", after: "$62", improvement: "-60%" },
      { label: "Revenue Growth", before: "$32K/mo", after: "$78K/mo", improvement: "+144%" },
    ],
    testimonial: { quote: "We're a small family shop competing against billion-dollar companies and we're winning. LexumSoft showed us how to turn our size into an advantage.", name: "Jack Patriot III", role: "Owner" },
    services: ["Google Ads", "Competitor Targeting", "Local Landing Pages", "Review Integration"],
    timeline: "90 days",
    heroStat: "189% More Leads",
  },
  {
    title: "HVAC Startup Gets 100 Leads in First Month",
    slug: "bluestar-heating-launch-ads",
    client: "BlueStar Heating & Air",
    industry: "Residential HVAC",
    category: "google-ads",
    featured: false,
    summary: "A brand-new HVAC company launched to a full pipeline of leads from day one with aggressive Google Ads campaigns.",
    challenge: "BlueStar Heating & Air was a brand-new company with zero online presence, no reviews, and no reputation. The owner left a larger HVAC company to start his own and needed leads immediately to cover his overhead.",
    solution: "We launched aggressive Google Ads campaigns on day one with compelling introductory offers. We set up a Google Business Profile with a review generation strategy, created a professional landing page, and implemented call tracking to measure every lead source.",
    results: "BlueStar generated 100 leads in their first month of operation. They booked 42 jobs worth over $55,000 in revenue. Within 90 days, they had 35 five-star Google reviews and a sustainable lead pipeline.",
    metrics: [
      { label: "First Month Leads", before: "0", after: "100", improvement: "New Business" },
      { label: "First Month Jobs", before: "0", after: "42", improvement: "New Business" },
      { label: "First Month Revenue", before: "$0", after: "$55K", improvement: "New Business" },
      { label: "Google Reviews (90 days)", before: "0", after: "35", improvement: "New Business" },
    ],
    testimonial: { quote: "I left my old company on a Friday and had my first lead on Monday. LexumSoft gave me the launch pad I needed to hit the ground running.", name: "Derek Simmons", role: "Founder" },
    services: ["Google Ads", "GBP Setup", "Review Generation", "Landing Pages"],
    timeline: "30 days",
    heroStat: "100 Leads in Month 1",
  },

  // ── SEO & Online Presence (12 projects) ──
  {
    title: "Plumber Goes from Page 5 to #1 on Google",
    slug: "westside-plumbing-seo",
    client: "Westside Plumbing",
    industry: "Residential Plumbing",
    category: "seo",
    featured: true,
    summary: "A plumbing company buried on page 5 of Google climbed to the #1 organic position and tripled their inbound leads.",
    challenge: "Westside Plumbing had a basic website that hadn't been updated in years. They were on page 5 of Google for every relevant keyword and received zero organic leads. All their business came from expensive ads and dwindling referrals.",
    solution: "We executed a comprehensive local SEO strategy — optimizing their Google Business Profile, building citations across 60+ directories, creating service area pages for each city they served, and writing keyword-rich content targeting buyer-intent searches.",
    results: "Within 6 months, Westside Plumbing ranked #1 for 'plumber near me' and 12 other high-value keywords. Organic traffic grew 840% and they now receive 45+ organic leads per month — all without paying for clicks.",
    metrics: [
      { label: "Google Ranking (Main KW)", before: "Page 5", after: "#1", improvement: "Page 1" },
      { label: "Organic Traffic", before: "120/mo", after: "1,128/mo", suffix: "/mo", improvement: "+840%" },
      { label: "Organic Leads", before: "0", after: "45", suffix: "/mo", improvement: "New" },
      { label: "Google Business Profile Views", before: "800/mo", after: "5,200/mo", improvement: "+550%" },
    ],
    testimonial: { quote: "We went from invisible to the #1 plumber on Google in our city. The organic leads alone replaced what we used to spend $4,000 a month on ads to get.", name: "James Westfield", role: "Owner" },
    services: ["Local SEO", "Google Business Profile", "Citation Building", "Content Strategy"],
    timeline: "6 months",
    heroStat: "#1 on Google",
  },
  {
    title: "HVAC Company Generates 200+ Google Reviews",
    slug: "greenleaf-hvac-reviews",
    client: "Greenleaf HVAC",
    industry: "Commercial HVAC",
    category: "seo",
    featured: false,
    summary: "A commercial HVAC company built a wall of 5-star reviews that dominates their local search results and builds instant trust.",
    challenge: "Greenleaf HVAC had only 12 Google reviews with a 3.8 rating, while their top competitor had 200+ reviews and a 4.8 rating. They were losing bids because prospects checked reviews first and chose the competitor with stronger social proof.",
    solution: "We implemented an automated review request system that texts customers after every completed job. We set up a review response workflow, trained their team on asking for reviews at the right moment, and created a review showcase page on their website.",
    results: "Greenleaf went from 12 reviews to 215 reviews in 8 months with a 4.9 average rating. Their Google Business Profile became the top result in the local pack, and inbound quote requests increased by 180%.",
    metrics: [
      { label: "Google Reviews", before: "12", after: "215", improvement: "+1692%" },
      { label: "Average Rating", before: "3.8", after: "4.9", suffix: "/5", improvement: "+29%" },
      { label: "Local Pack Ranking", before: "#5", after: "#1", improvement: "#1 Spot" },
      { label: "Inbound Quote Requests", before: "10/mo", after: "28/mo", suffix: "/mo", improvement: "+180%" },
    ],
    testimonial: { quote: "We used to lose bids to companies with better reviews. Now we're the most-reviewed HVAC company in the region. Customers tell us they chose us because of our reviews.", name: "Linda Chen", role: "Business Development Manager" },
    services: ["Review Generation", "Review Management", "Google Business Profile", "Reputation Marketing"],
    timeline: "8 months",
    heroStat: "215 Five-Star Reviews",
  },
  {
    title: "Plumber Captures 15 Service Area Cities",
    slug: "trueflow-plumbing-local-seo",
    client: "TrueFlow Plumbing",
    industry: "Residential Plumbing",
    category: "seo",
    featured: false,
    summary: "A plumbing company expanded its SEO footprint to rank in 15 nearby cities, tripling their serviceable market.",
    challenge: "TrueFlow Plumbing only ranked for keywords in their home city. They served 15 surrounding communities but had zero visibility in those areas. Competitors in each city were capturing all the local search traffic.",
    solution: "We created unique, optimized service area pages for each of the 15 cities with localized content, area-specific testimonials, and embedded maps. We built local citations for each area and optimized the Google Business Profile service area settings.",
    results: "TrueFlow now ranks on page 1 in 12 of their 15 target cities. Their total organic traffic grew by 420% and they expanded their team from 4 to 8 technicians to cover the increased service area demand.",
    metrics: [
      { label: "Cities Ranked (Page 1)", before: "1", after: "12", improvement: "+1100%" },
      { label: "Organic Traffic", before: "450/mo", after: "2,340/mo", suffix: "/mo", improvement: "+420%" },
      { label: "Monthly Organic Leads", before: "8", after: "52", suffix: "/mo", improvement: "+550%" },
      { label: "Service Area Coverage", before: "1 city", after: "15 cities", improvement: "15x" },
    ],
    testimonial: { quote: "We were stuck in one city. Now we rank in 12 different communities and our service area effectively tripled overnight. The growth has been incredible.", name: "Nathan Price", role: "Owner" },
    services: ["Local SEO", "Service Area Pages", "Citation Building", "Content Creation"],
    timeline: "6 months",
    heroStat: "12 Cities on Page 1",
  },
  {
    title: "HVAC Brand Builds 5,000 Monthly Organic Visitors",
    slug: "comfort-zone-organic-traffic",
    client: "Comfort Zone HVAC",
    industry: "Residential HVAC",
    category: "seo",
    featured: false,
    summary: "An HVAC company built a content engine that drives 5,000 monthly organic visitors and positions them as the local authority.",
    challenge: "Comfort Zone HVAC had a brochure-style website with just 5 pages and no blog. Their organic traffic was under 200 visitors per month and they were entirely dependent on paid advertising for leads.",
    solution: "We developed a content strategy with 40+ HVAC educational articles targeting informational keywords. We created comprehensive guides on furnace maintenance, AC troubleshooting, and energy efficiency. Internal linking and schema markup amplified SEO performance.",
    results: "Organic traffic grew from 180 to 5,200 monthly visitors. Their content generates 35+ leads per month from homeowners researching HVAC topics. They've reduced their ad spend by 40% while maintaining total lead volume.",
    metrics: [
      { label: "Monthly Organic Traffic", before: "180", after: "5,200", suffix: "/mo", improvement: "+2789%" },
      { label: "Organic Leads", before: "2", after: "35", suffix: "/mo", improvement: "+1650%" },
      { label: "Indexed Pages", before: "5", after: "52", improvement: "+940%" },
      { label: "Ad Spend Reduction", before: "$4.5K/mo", after: "$2.7K/mo", improvement: "-40%" },
    ],
    testimonial: { quote: "Our blog now generates more leads than our ads used to. Homeowners find our guides, trust our expertise, and call us. It's the best marketing investment we've ever made.", name: "Steve Martinez", role: "Owner" },
    services: ["Content Strategy", "Blog Writing", "On-Page SEO", "Schema Markup"],
    timeline: "6 months",
    heroStat: "5,200 Monthly Visitors",
  },
  {
    title: "Plumbing Company Ranks for 85 Local Keywords",
    slug: "eagle-plumbing-keyword-dominance",
    client: "Eagle Plumbing Solutions",
    industry: "Residential Plumbing",
    category: "seo",
    featured: false,
    summary: "A plumbing company went from ranking for 5 keywords to 85, capturing search traffic across every service they offer.",
    challenge: "Eagle Plumbing only ranked for generic terms like 'plumber' in their city. They offered 20+ specialized services but had zero keyword visibility for specific searches like 'water heater installation' or 'sewer line repair.'",
    solution: "We conducted deep keyword research to identify 100+ target keywords across all service categories. We optimized existing pages, created new service-specific pages, and built supporting content clusters around each core service category.",
    results: "Eagle Plumbing now ranks on page 1 for 85 local keywords across all their service categories. Their organic lead volume increased by 340%, and they're consistently ranked above national chains in local results.",
    metrics: [
      { label: "Page 1 Keywords", before: "5", after: "85", improvement: "+1600%" },
      { label: "Organic Leads/Month", before: "5", after: "22", suffix: "/mo", improvement: "+340%" },
      { label: "Organic Traffic", before: "310/mo", after: "3,400/mo", suffix: "/mo", improvement: "+997%" },
      { label: "Service Pages Ranking", before: "1", after: "18", improvement: "+1700%" },
    ],
    testimonial: { quote: "We used to only show up when someone searched 'plumber.' Now we rank for every service we offer. People find us no matter what plumbing problem they have.", name: "Paul Eagle", role: "Owner" },
    services: ["Keyword Research", "On-Page SEO", "Service Pages", "Content Clusters"],
    timeline: "6 months",
    heroStat: "85 Keywords on Page 1",
  },
  {
    title: "Commercial HVAC Firm Dominates Google Maps",
    slug: "pureair-systems-maps",
    client: "PureAir Systems",
    industry: "Commercial HVAC",
    category: "seo",
    featured: false,
    summary: "A commercial HVAC company claimed the top Google Maps position and now gets 60% of their new leads from organic search.",
    challenge: "PureAir Systems didn't even have a claimed Google Business Profile. They were invisible in Google Maps while competitors dominated the local pack. Commercial clients couldn't find them online when searching for HVAC services.",
    solution: "We claimed and fully optimized their Google Business Profile with detailed services, photos, Q&A, and regular posts. We implemented a review generation campaign and built consistent NAP citations across 80+ business directories.",
    results: "PureAir rose to the #1 position in Google Maps for commercial HVAC keywords. Their GBP now generates 60+ calls and 25+ quote requests per month. Organic search accounts for 60% of all new business.",
    metrics: [
      { label: "Google Maps Position", before: "Not Listed", after: "#1", improvement: "Top Spot" },
      { label: "GBP Monthly Calls", before: "0", after: "62", suffix: "/mo", improvement: "New" },
      { label: "Monthly Quote Requests", before: "4", after: "29", suffix: "/mo", improvement: "+625%" },
      { label: "Leads from Organic", before: "10%", after: "60%", suffix: "%", improvement: "+500%" },
    ],
    testimonial: { quote: "We didn't even know we needed a Google Business Profile. Now it's responsible for more than half our new business. We should have done this years ago.", name: "Marcus Green", role: "CEO" },
    services: ["Google Business Profile", "Citation Building", "Review Generation", "Local SEO"],
    timeline: "4 months",
    heroStat: "#1 on Google Maps",
  },
  {
    title: "Plumbing Website Becomes Top Local Resource",
    slug: "cascade-plumbing-content-seo",
    client: "Cascade Plumbing",
    industry: "Residential Plumbing",
    category: "seo",
    featured: false,
    summary: "A plumbing company's website became the go-to local resource for plumbing advice, generating trust and a flood of leads.",
    challenge: "Cascade Plumbing had zero content on their website beyond basic service descriptions. Homeowners in their area were finding plumbing advice on national sites that then recommended competitors. They were losing the top of the funnel entirely.",
    solution: "We built a comprehensive content hub with seasonal plumbing maintenance guides, DIY vs. professional guides, and cost comparison articles. Every piece of content included lead magnets like downloadable checklists and links to request service.",
    results: "Cascade's website became the most-visited plumbing resource in their metro area. Their bounce rate dropped by 45%, average session duration tripled, and they now generate 40+ inbound calls per month from organic content.",
    metrics: [
      { label: "Monthly Organic Visitors", before: "250", after: "4,800", suffix: "/mo", improvement: "+1820%" },
      { label: "Avg Session Duration", before: "0:45", after: "2:35", improvement: "+244%" },
      { label: "Organic Calls/Month", before: "3", after: "42", suffix: "/mo", improvement: "+1300%" },
      { label: "Bounce Rate", before: "78%", after: "33%", suffix: "%", improvement: "-58%" },
    ],
    testimonial: { quote: "People call us saying they read our guide online and want to hire us. Our website went from a digital business card to our most powerful sales tool.", name: "Diane Cascade", role: "Owner" },
    services: ["Content Strategy", "Blog Writing", "Lead Magnets", "On-Page SEO"],
    timeline: "6 months",
    heroStat: "1820% Traffic Growth",
  },
  {
    title: "Heating Company Wins Featured Snippets",
    slug: "northwind-heating-snippets",
    client: "Northwind Heating",
    industry: "Residential HVAC",
    category: "seo",
    featured: false,
    summary: "An HVAC company earned Google's featured snippets for 8 high-volume queries, positioning them as the top authority.",
    challenge: "Northwind Heating had decent organic rankings but was stuck in positions 4-7 for their most valuable keywords. They needed to break through to the top of search results without increasing their ad spend.",
    solution: "We restructured their content with snippet-friendly formatting — clear headings, concise answers, comparison tables, and FAQ sections. We optimized for voice search and 'People Also Ask' boxes with question-based content.",
    results: "Northwind earned featured snippets for 8 high-volume heating keywords. Their click-through rate from search results doubled, and organic traffic jumped by 180%. They're now considered the local authority on heating services.",
    metrics: [
      { label: "Featured Snippets Won", before: "0", after: "8", improvement: "New" },
      { label: "Organic CTR", before: "3.2%", after: "8.5%", suffix: "%", improvement: "+166%" },
      { label: "Organic Traffic", before: "1,200/mo", after: "3,360/mo", suffix: "/mo", improvement: "+180%" },
      { label: "Brand Search Volume", before: "40/mo", after: "220/mo", suffix: "/mo", improvement: "+450%" },
    ],
    testimonial: { quote: "When people ask Google a heating question, our answer shows up first. That kind of authority is priceless. Our brand recognition has skyrocketed.", name: "William North", role: "Owner" },
    services: ["Content Optimization", "Featured Snippets", "Voice Search SEO", "FAQ Schema"],
    timeline: "4 months",
    heroStat: "8 Featured Snippets",
  },
  {
    title: "Commercial Plumber Wins Enterprise Clients via SEO",
    slug: "pipemaster-pro-b2b-seo",
    client: "PipeMaster Pro",
    industry: "Commercial Plumbing",
    category: "seo",
    featured: false,
    summary: "A commercial plumbing firm used B2B SEO to attract property managers and GCs, landing $500K in new annual contracts.",
    challenge: "PipeMaster Pro served commercial clients but their website looked residential. Property managers and general contractors searching for commercial plumbing services couldn't distinguish them from residential plumbers in search results.",
    solution: "We rebuilt their online presence with a B2B focus — creating dedicated pages for commercial services, adding case studies from past projects, implementing industry-specific schema markup, and targeting commercial-intent keywords.",
    results: "PipeMaster now ranks #1 for 'commercial plumber' in their metro area. They landed 8 new long-term commercial contracts worth $500K in annual revenue. Their website conversion rate for commercial inquiries went from 0.5% to 4.2%.",
    metrics: [
      { label: "Commercial Keyword Rank", before: "Not ranked", after: "#1", improvement: "Top Spot" },
      { label: "Commercial Inquiries/Month", before: "3", after: "22", suffix: "/mo", improvement: "+633%" },
      { label: "New Annual Contracts", before: "$60K", after: "$500K", improvement: "+733%" },
      { label: "Website Conversion Rate", before: "0.5%", after: "4.2%", suffix: "%", improvement: "+740%" },
    ],
    testimonial: { quote: "General contractors now find us first when they need a commercial plumber. We've signed more contracts this year than in the previous three years combined.", name: "George Masters", role: "President" },
    services: ["B2B SEO", "Commercial Service Pages", "Case Studies", "Schema Markup"],
    timeline: "6 months",
    heroStat: "$500K in Contracts",
  },
  {
    title: "HVAC Company Builds Referral Engine with Reviews",
    slug: "frostguard-hvac-referrals",
    client: "FrostGuard HVAC",
    industry: "Residential HVAC",
    category: "seo",
    featured: false,
    summary: "An HVAC company turned their review strategy into a referral engine that generates 30% of all new business automatically.",
    challenge: "FrostGuard had excellent service quality but no system for capturing reviews or leveraging social proof. Happy customers rarely left reviews and their 18 total reviews didn't reflect the quality of their 15 years in business.",
    solution: "We built a multi-touchpoint review system — automated text requests, email follow-ups, and QR codes on invoices. We created a review showcase wall on their website and social sharing templates. Happy reviewers received referral incentives for sharing with neighbors.",
    results: "FrostGuard grew from 18 to 340 reviews with a 4.9 rating. Their review-to-referral system now generates 30% of all new leads automatically. Customer acquisition cost dropped by 52%.",
    metrics: [
      { label: "Google Reviews", before: "18", after: "340", improvement: "+1789%" },
      { label: "Leads from Reviews/Referrals", before: "5%", after: "30%", suffix: "%", improvement: "+500%" },
      { label: "Customer Acquisition Cost", before: "$185", after: "$89", improvement: "-52%" },
      { label: "Monthly Referral Leads", before: "2", after: "18", suffix: "/mo", improvement: "+800%" },
    ],
    testimonial: { quote: "Our reviews now sell for us. Customers tell us they chose us because of what others said. The referral system is like having a free sales team.", name: "Chris Frost", role: "Owner" },
    services: ["Review Generation", "Referral System", "Social Proof Marketing", "Email Automation"],
    timeline: "6 months",
    heroStat: "340 Five-Star Reviews",
  },
  {
    title: "Plumber Reclaims Online Reputation After Bad Reviews",
    slug: "riverview-plumbing-reputation",
    client: "Riverview Plumbing",
    industry: "Residential Plumbing",
    category: "seo",
    featured: false,
    summary: "A plumbing company recovered from a 2.8-star rating to 4.8 stars with strategic reputation management and review recovery.",
    challenge: "Riverview Plumbing had a 2.8-star Google rating after a string of negative reviews from a bad employee who was since fired. The low rating was killing their business — call volume dropped 60% and they were losing bids to competitors.",
    solution: "We implemented a reputation recovery strategy — responding professionally to every negative review, flagging fraudulent ones, and launching an aggressive positive review campaign. We set up a review funnel that directed happy customers to Google and unhappy customers to a private feedback form.",
    results: "Riverview's rating climbed from 2.8 to 4.8 stars within 5 months. Call volume returned to pre-crisis levels and then exceeded them by 40%. The smart review funnel prevents future reputation damage.",
    metrics: [
      { label: "Google Rating", before: "2.8", after: "4.8", suffix: "/5", improvement: "+71%" },
      { label: "Monthly Calls", before: "25", after: "85", suffix: "/mo", improvement: "+240%" },
      { label: "New Reviews (5 months)", before: "8 negative", after: "180 positive", improvement: "Recovered" },
      { label: "Revenue Recovery", before: "-60%", after: "+40%", improvement: "Full Recovery" },
    ],
    testimonial: { quote: "One bad employee almost destroyed our 20-year reputation. LexumSoft not only fixed it — they made our online presence stronger than it's ever been.", name: "Al Rivera", role: "Owner" },
    services: ["Reputation Management", "Review Recovery", "Review Funnel", "Crisis Response"],
    timeline: "5 months",
    heroStat: "2.8 to 4.8 Stars",
  },
  {
    title: "HVAC Contractor Outranks 3 National Franchises",
    slug: "tempright-hvac-franchise-seo",
    client: "TempRight HVAC",
    industry: "Commercial HVAC",
    category: "seo",
    featured: false,
    summary: "An independent HVAC contractor outranked three national franchise brands in local organic search results.",
    challenge: "TempRight HVAC was competing against three national HVAC franchises with massive domain authority and nationwide SEO teams. Despite excellent service, they were buried beneath franchise results for every local search.",
    solution: "We exploited the franchises' weaknesses — generic content, poor local optimization, and slow response times. We built hyper-local content, earned backlinks from local organizations, and optimized for neighborhood-level keywords the franchises couldn't target.",
    results: "TempRight now outranks all three national franchises in organic search for their metro area. Their organic traffic exceeds the combined local traffic of all three franchise competitors. They've grown revenue by $180K annually from organic alone.",
    metrics: [
      { label: "Organic Rank vs Franchises", before: "Below all 3", after: "Above all 3", improvement: "#1 Local" },
      { label: "Monthly Organic Traffic", before: "380", after: "3,800", suffix: "/mo", improvement: "+900%" },
      { label: "Local Backlinks", before: "5", after: "85", improvement: "+1600%" },
      { label: "Annual Revenue from SEO", before: "$20K", after: "$200K", improvement: "+900%" },
    ],
    testimonial: { quote: "We beat three national chains in organic search results. Their SEO budgets are 100x ours but LexumSoft's local strategy is simply better.", name: "Kevin Templeton", role: "Owner" },
    services: ["Local SEO", "Link Building", "Competitor Analysis", "Hyper-Local Content"],
    timeline: "8 months",
    heroStat: "Outranks 3 Franchises",
  },

  // ── Website Design (10 projects) ──
  {
    title: "New Website Converts 5x More Visitors into Leads",
    slug: "proflow-plumbing-website",
    client: "ProFlow Plumbing & Heating",
    industry: "Residential Plumbing",
    category: "website-design",
    featured: true,
    summary: "A dated website was replaced with a conversion-optimized design that 5x'd their lead capture rate overnight.",
    challenge: "ProFlow's website looked like it was built in 2008. It wasn't mobile-friendly, had no clear calls to action, and loaded in over 8 seconds. Despite decent traffic, only 1.2% of visitors ever contacted them. They were leaving thousands in revenue on the table.",
    solution: "We designed a modern, mobile-first website with prominent click-to-call buttons, a trust-building design system featuring reviews and certifications, and fast-loading pages optimized for Core Web Vitals. Every page was designed as a conversion funnel.",
    results: "ProFlow's website conversion rate jumped from 1.2% to 6.1% — a 5x improvement. With the same traffic, they went from 8 leads per month to 41. Page load time dropped from 8 seconds to 1.4 seconds, and bounce rate dropped by 55%.",
    metrics: [
      { label: "Conversion Rate", before: "1.2%", after: "6.1%", suffix: "%", improvement: "+408%" },
      { label: "Monthly Leads", before: "8", after: "41", suffix: "/mo", improvement: "+413%" },
      { label: "Page Load Time", before: "8.2s", after: "1.4s", improvement: "-83%" },
      { label: "Bounce Rate", before: "72%", after: "32%", suffix: "%", improvement: "-56%" },
    ],
    testimonial: { quote: "Our old website was embarrassing. The new one looks incredible and actually gets us leads. We went from 8 leads a month to over 40 without spending a dime more on ads.", name: "David Chen", role: "Founder" },
    services: ["Website Design", "Mobile Optimization", "Speed Optimization", "Conversion Rate Optimization"],
    timeline: "30 days",
    heroStat: "5x More Conversions",
  },
  {
    title: "HVAC Website Redesign Generates $30K in First Month",
    slug: "climatecraft-hvac-redesign",
    client: "ClimateCraft HVAC",
    industry: "Residential HVAC",
    category: "website-design",
    featured: false,
    summary: "A complete HVAC website redesign turned a digital brochure into a lead-generating machine from day one.",
    challenge: "ClimateCraft's website was a single-page template with no service details, no social proof, and a broken contact form. Mobile users — 70% of their traffic — had to pinch and zoom just to read the text. They averaged one website lead per month.",
    solution: "We built a custom HVAC website with dedicated service pages, financing calculators, seasonal promotion banners, and integrated review feeds. The mobile experience was redesigned from scratch with thumb-friendly navigation and persistent call buttons.",
    results: "ClimateCraft generated $30K in revenue from website leads in the first month after launch. Monthly leads grew from 1 to 24, and their mobile conversion rate increased by 800%. The site became their #1 lead source.",
    metrics: [
      { label: "Monthly Website Leads", before: "1", after: "24", suffix: "/mo", improvement: "+2300%" },
      { label: "First Month Revenue", before: "$800", after: "$30K", improvement: "+3650%" },
      { label: "Mobile Conversion Rate", before: "0.3%", after: "2.7%", suffix: "%", improvement: "+800%" },
      { label: "Average Pages Per Visit", before: "1.2", after: "3.8", improvement: "+217%" },
    ],
    testimonial: { quote: "Our website used to be a joke. Now it's a lead machine. We made more from website leads in the first month than in the entire previous year.", name: "Angela Craft", role: "Marketing Manager" },
    services: ["Website Design", "Mobile Design", "Service Pages", "Review Integration"],
    timeline: "45 days",
    heroStat: "$30K in Month 1",
  },
  {
    title: "Plumbing Website Scores Perfect Core Web Vitals",
    slug: "aquaguard-plumbing-performance",
    client: "AquaGuard Plumbing",
    industry: "Residential Plumbing",
    category: "website-design",
    featured: false,
    summary: "A slow, bloated plumbing website was rebuilt into a lightning-fast site with perfect Google performance scores.",
    challenge: "AquaGuard's WordPress website was loaded with plugins, unoptimized images, and bloated code. It scored 18/100 on Google PageSpeed and took 12 seconds to load. Google was actively penalizing them in search rankings due to poor performance.",
    solution: "We rebuilt the site on Next.js with optimized images, lazy loading, and clean code. Every design element was purpose-built for performance without sacrificing visual quality. We implemented proper caching, CDN delivery, and modern image formats.",
    results: "AquaGuard's website now scores 98/100 on PageSpeed and loads in under 1 second. Google's Core Web Vitals penalty was lifted, resulting in a 45% boost in organic traffic within 60 days.",
    metrics: [
      { label: "PageSpeed Score", before: "18", after: "98", suffix: "/100", improvement: "+444%" },
      { label: "Load Time", before: "12s", after: "0.8s", improvement: "-93%" },
      { label: "Organic Traffic (60 days)", before: "600/mo", after: "870/mo", suffix: "/mo", improvement: "+45%" },
      { label: "Core Web Vitals", before: "Failing", after: "All Passing", improvement: "Fixed" },
    ],
    testimonial: { quote: "Our website loads instantly now. Customers comment on how professional and fast it is. The organic traffic boost we got from fixing our speed was a huge bonus.", name: "Tony Aguilar", role: "Owner" },
    services: ["Website Rebuild", "Performance Optimization", "Core Web Vitals", "Next.js Development"],
    timeline: "30 days",
    heroStat: "98/100 PageSpeed",
  },
  {
    title: "HVAC Company Gets Website That Sells 24/7",
    slug: "breeze-masters-hvac-website",
    client: "Breeze Masters HVAC",
    industry: "Commercial HVAC",
    category: "website-design",
    featured: false,
    summary: "A commercial HVAC company got a professional website that works as a 24/7 sales rep, booking estimates while they sleep.",
    challenge: "Breeze Masters had no website at all — just a Facebook page and a Yelp listing. They lost a major contract because the property management company said they 'couldn't take a company seriously that doesn't even have a website.'",
    solution: "We built a professional commercial HVAC website with project galleries, capability statements, certifications, and a sophisticated estimate request system. We integrated a chatbot for instant response and created downloadable spec sheets for each service.",
    results: "Breeze Masters landed three new commercial contracts within the first month of launching their website. Their estimate requests went from 2 per month (via phone) to 18 per month. The chatbot alone captured 6 leads per month outside business hours.",
    metrics: [
      { label: "Monthly Estimate Requests", before: "2", after: "18", suffix: "/mo", improvement: "+800%" },
      { label: "New Commercial Contracts", before: "0", after: "3 (month 1)", improvement: "New" },
      { label: "After-Hours Lead Capture", before: "0", after: "6/mo", suffix: "/mo", improvement: "New" },
      { label: "Professional Credibility", before: "No website", after: "Industry-leading", improvement: "Established" },
    ],
    testimonial: { quote: "We lost a $200K contract because we didn't have a website. That will never happen again. Our site now closes deals while we're out on jobs.", name: "Terrence Breeze", role: "Owner" },
    services: ["Website Design", "Commercial Branding", "Chatbot Integration", "Lead Capture"],
    timeline: "45 days",
    heroStat: "800% More Estimates",
  },
  {
    title: "Plumbing Brand Gets Premium Website That Builds Trust",
    slug: "capital-plumbing-brand-site",
    client: "Capital Plumbing",
    industry: "Residential Plumbing",
    category: "website-design",
    featured: false,
    summary: "A premium plumbing company got a website that reflects their quality and justifies their higher-than-average prices.",
    challenge: "Capital Plumbing charged premium prices for premium work, but their cheap template website undermined their positioning. Customers questioned why they should pay more when the website looked the same as budget competitors.",
    solution: "We designed a premium brand experience with high-end visuals, before/after project galleries, a detailed process walkthrough, and prominent trust signals including licensing, insurance, and warranty information. The design communicated quality at every touchpoint.",
    results: "Capital Plumbing's average job value increased by 28% as the website justified their premium pricing. Customer objections about price dropped significantly. Their close rate on estimates improved from 35% to 52%.",
    metrics: [
      { label: "Average Job Value", before: "$420", after: "$538", improvement: "+28%" },
      { label: "Estimate Close Rate", before: "35%", after: "52%", suffix: "%", improvement: "+49%" },
      { label: "Website Trust Score", before: "Low", after: "Premium", improvement: "Elevated" },
      { label: "Monthly Revenue", before: "$38K", after: "$62K", improvement: "+63%" },
    ],
    testimonial: { quote: "Our website finally matches the quality of our work. Customers no longer question our prices — the website sells them before we even pick up the phone.", name: "Ryan Chambers", role: "Owner" },
    services: ["Premium Website Design", "Brand Strategy", "Project Gallery", "Trust Optimization"],
    timeline: "45 days",
    heroStat: "28% Higher Job Value",
  },
  {
    title: "HVAC Website with Built-In Scheduling Books 50 Jobs/Month",
    slug: "freshair-hvac-scheduling-site",
    client: "FreshAir HVAC Solutions",
    industry: "Residential HVAC",
    category: "website-design",
    featured: false,
    summary: "An HVAC website with integrated self-scheduling lets customers book service online, eliminating phone tag entirely.",
    challenge: "FreshAir's dispatchers spent hours playing phone tag with customers trying to schedule service. 40% of callers hung up on hold, and they had no way for customers to self-schedule online. They estimated losing 15 jobs per month to appointment friction.",
    solution: "We built a website with an integrated online scheduling system showing real-time availability. Customers could select their service type, choose a time slot, and receive instant confirmation. The system synced with their dispatch software and sent automated reminders.",
    results: "Online bookings now account for 50% of all appointments. Phone hold times dropped to near zero. FreshAir went from 35 to 50 booked jobs per month, and customer satisfaction scores increased dramatically.",
    metrics: [
      { label: "Monthly Booked Jobs", before: "35", after: "50", suffix: "/mo", improvement: "+43%" },
      { label: "Online Bookings", before: "0%", after: "50%", suffix: "%", improvement: "New Channel" },
      { label: "Abandoned Calls", before: "40%", after: "8%", suffix: "%", improvement: "-80%" },
      { label: "Scheduling Efficiency", before: "15 min/call", after: "Automated", improvement: "Automated" },
    ],
    testimonial: { quote: "Customers love booking online. Our dispatchers aren't drowning in calls anymore, and we book 15 more jobs per month than before. It's been a game-changer.", name: "Sarah Livingston", role: "Office Manager" },
    services: ["Website Design", "Online Scheduling", "CRM Integration", "Automation"],
    timeline: "60 days",
    heroStat: "50% Book Online",
  },
  {
    title: "Plumbing Website Generates Leads in 3 Languages",
    slug: "golden-state-multilingual-site",
    client: "Golden State Plumbing",
    industry: "Residential Plumbing",
    category: "website-design",
    featured: false,
    summary: "A multilingual plumbing website captured an underserved Spanish and Chinese-speaking market for a California plumber.",
    challenge: "Golden State Plumbing served a diverse community where 45% of residents spoke Spanish or Chinese as their primary language. Their English-only website was invisible to nearly half their potential market, and competitors weren't serving these communities either.",
    solution: "We built a fully translated website in English, Spanish, and Chinese with culturally appropriate design elements. Each language version was SEO-optimized for language-specific keywords. We set up bilingual call tracking and created ads in all three languages.",
    results: "Golden State's total addressable market expanded by 45%. They captured an entirely new customer base, adding 28 Spanish-language and 12 Chinese-language leads per month. Revenue grew by 55% within 4 months.",
    metrics: [
      { label: "Total Monthly Leads", before: "32", after: "72", suffix: "/mo", improvement: "+125%" },
      { label: "Spanish-Language Leads", before: "0", after: "28", suffix: "/mo", improvement: "New" },
      { label: "Chinese-Language Leads", before: "0", after: "12", suffix: "/mo", improvement: "New" },
      { label: "Revenue Growth", before: "$0", after: "+55%", improvement: "+55%" },
    ],
    testimonial: { quote: "We tapped into a market our competitors completely ignored. Almost 40 new leads per month from Spanish and Chinese-speaking customers who couldn't find a plumber in their language.", name: "Victor Huang", role: "Owner" },
    services: ["Multilingual Website", "Translation SEO", "Cultural Localization", "Bilingual Ads"],
    timeline: "60 days",
    heroStat: "125% More Leads",
  },
  {
    title: "HVAC Franchise Gets Custom Location Pages",
    slug: "reliable-climate-franchise-sites",
    client: "Reliable Climate Systems",
    industry: "Commercial HVAC",
    category: "website-design",
    featured: false,
    summary: "A multi-location HVAC company got custom pages for each location that rank locally and drive leads to the right office.",
    challenge: "Reliable Climate had 6 locations but a single generic website. Customers couldn't tell which location served their area. Each location had different services and hours, but the website didn't reflect this. They were losing leads to confusion.",
    solution: "We created unique location pages for all 6 offices with localized content, team photos, service-area maps, and location-specific reviews. Each page was optimized for local SEO and had its own tracking number to attribute leads to the correct branch.",
    results: "Combined leads across all locations increased by 150%. Each location now ranks independently in their local market. The location-specific tracking revealed which branches needed more marketing support.",
    metrics: [
      { label: "Total Monthly Leads", before: "40", after: "100", suffix: "/mo", improvement: "+150%" },
      { label: "Location Pages Ranking", before: "0", after: "6/6", improvement: "All Ranking" },
      { label: "Lead Attribution Accuracy", before: "Unknown", after: "100%", suffix: "%", improvement: "Solved" },
      { label: "Per-Location Avg Leads", before: "6.7", after: "16.7", suffix: "/mo", improvement: "+149%" },
    ],
    testimonial: { quote: "Each location now has its own online identity. We can see exactly which offices generate leads and which need help. It's transformed how we manage our multi-location business.", name: "Pat O'Brien", role: "Regional Director" },
    services: ["Multi-Location Website", "Location Pages", "Local SEO", "Lead Attribution"],
    timeline: "60 days",
    heroStat: "150% More Leads",
  },
  {
    title: "Plumber's DIY Site Replaced with Pro Design",
    slug: "safepipe-plumbing-pro-redesign",
    client: "SafePipe Plumbing",
    industry: "Residential Plumbing",
    category: "website-design",
    featured: false,
    summary: "A Wix DIY website was replaced with a professional design that finally matched the quality of their plumbing work.",
    challenge: "SafePipe's owner built their website on Wix years ago. It had clip art images, walls of text, Comic Sans font, and a contact form that didn't work. Customers literally told them they almost didn't call because the website looked unprofessional.",
    solution: "We replaced the DIY site with a professionally designed website featuring real project photos, clean typography, and intuitive navigation. We added click-to-call buttons, a working lead form, and integrated their Google reviews directly on the homepage.",
    results: "Website leads increased from near-zero to 22 per month. Customer feedback about the website went from negative to overwhelmingly positive. SafePipe's owner said 'it looks like a million-dollar company' for the first time.",
    metrics: [
      { label: "Monthly Website Leads", before: "1", after: "22", suffix: "/mo", improvement: "+2100%" },
      { label: "Mobile Usability Score", before: "35", after: "99", suffix: "/100", improvement: "+183%" },
      { label: "Time on Site", before: "0:22", after: "1:45", improvement: "+377%" },
      { label: "Customer Perception", before: "Unprofessional", after: "Premium", improvement: "Transformed" },
    ],
    testimonial: { quote: "I'm embarrassed we ran that old website for so long. The new one looks like a company 10 times our size. Customers trust us immediately now.", name: "Ed Safetti", role: "Owner" },
    services: ["Website Redesign", "Professional Photography", "Brand Upgrade", "Lead Generation"],
    timeline: "30 days",
    heroStat: "2100% More Leads",
  },
  {
    title: "HVAC Website with Financing Calculator Boosts Installs",
    slug: "thermotech-hvac-financing-site",
    client: "ThermoTech HVAC",
    industry: "Residential HVAC",
    category: "website-design",
    featured: false,
    summary: "An HVAC website with a built-in financing calculator increased installation sales by removing the price objection.",
    challenge: "ThermoTech sold high-ticket HVAC installations ($8K-$15K) but their website only showed 'call for pricing.' Customers experienced sticker shock on the phone and 60% dropped off before scheduling an estimate.",
    solution: "We built a website with an interactive financing calculator that showed monthly payment options. Customers could see that a $12,000 AC system was only $89/month with approved credit. We added financing pre-qualification forms and payment comparison tools.",
    results: "Installation lead volume increased by 65% and the close rate on high-ticket installations improved from 22% to 41%. The financing calculator was used 400+ times per month and dramatically reduced price objection calls.",
    metrics: [
      { label: "Installation Leads", before: "14/mo", after: "23/mo", suffix: "/mo", improvement: "+65%" },
      { label: "High-Ticket Close Rate", before: "22%", after: "41%", suffix: "%", improvement: "+86%" },
      { label: "Calculator Uses/Month", before: "N/A", after: "420", suffix: "/mo", improvement: "New" },
      { label: "Monthly Install Revenue", before: "$42K", after: "$92K", improvement: "+119%" },
    ],
    testimonial: { quote: "The financing calculator removed the biggest objection we faced. Customers see $89/month instead of $12,000 and suddenly a new AC system is affordable.", name: "Jason Thermo", role: "Sales Manager" },
    services: ["Website Design", "Financing Calculator", "Conversion Optimization", "Payment Integration"],
    timeline: "45 days",
    heroStat: "86% Better Close Rate",
  },

  // ── AI Receptionist (8 projects) ──
  {
    title: "Plumber Captures 40% More After-Hours Leads",
    slug: "elite-plumbing-ai-receptionist",
    client: "Elite Plumbing Services",
    industry: "Residential Plumbing",
    category: "ai-receptionist",
    featured: false,
    summary: "An AI receptionist captures every after-hours call, turning missed opportunities into booked jobs for a busy plumbing company.",
    challenge: "Elite Plumbing missed 40% of their incoming calls — most during evenings, weekends, and holidays when their office was closed. Each missed call represented a potential $500-$2,000 job going straight to a competitor.",
    solution: "We deployed our AI receptionist to answer every call outside business hours. It greets callers naturally, qualifies the job type and urgency, collects contact information, and either schedules a callback or dispatches an emergency technician for urgent issues.",
    results: "Elite Plumbing now captures 100% of incoming calls. Their after-hours lead capture increased by 40%, adding $12,000 per month in new revenue. Emergency dispatch calls are routed instantly, improving response times from hours to minutes.",
    metrics: [
      { label: "Call Answer Rate", before: "60%", after: "100%", suffix: "%", improvement: "+67%" },
      { label: "After-Hours Leads", before: "5/wk", after: "14/wk", suffix: "/wk", improvement: "+180%" },
      { label: "Monthly Revenue from AI", before: "$0", after: "$12K", suffix: "/mo", improvement: "New" },
      { label: "Emergency Response Time", before: "2+ hours", after: "8 minutes", improvement: "-93%" },
    ],
    testimonial: { quote: "The AI receptionist pays for itself ten times over every month. We went from missing half our calls to never missing one. It sounds so natural that customers don't even realize it's AI.", name: "Marcus Elite", role: "Owner" },
    services: ["AI Receptionist", "After-Hours Answering", "Emergency Dispatch", "Lead Qualification"],
    timeline: "14 days",
    heroStat: "40% More Leads",
  },
  {
    title: "HVAC Company Saves $3,000/Month Replacing Answering Service",
    slug: "nextgen-hvac-ai-savings",
    client: "NextGen HVAC",
    industry: "Residential HVAC",
    category: "ai-receptionist",
    featured: false,
    summary: "An HVAC company replaced their expensive answering service with AI, saving $3,000/month while improving call quality.",
    challenge: "NextGen HVAC was paying $4,200/month for a human answering service that frequently botched messages, couldn't answer technical questions, and put callers on hold during peak times. They needed better call handling at a lower cost.",
    solution: "We replaced their answering service with our AI receptionist trained on HVAC terminology and NextGen's specific services. The AI handles scheduling, answers common questions about pricing and services, and never puts callers on hold.",
    results: "NextGen saves $3,000/month compared to their old answering service. Customer satisfaction with phone interactions increased from 3.2 to 4.7 out of 5. The AI handles 200+ calls per month without a single complaint.",
    metrics: [
      { label: "Monthly Cost", before: "$4,200", after: "$1,200", improvement: "-71%" },
      { label: "Call Satisfaction Score", before: "3.2/5", after: "4.7/5", improvement: "+47%" },
      { label: "Average Hold Time", before: "3.5 min", after: "0 sec", improvement: "-100%" },
      { label: "Monthly Calls Handled", before: "180", after: "220", suffix: "/mo", improvement: "+22%" },
    ],
    testimonial: { quote: "We cut our phone costs by 71% and our callers are happier. The AI knows our services better than the old answering service ever did. It's honestly better than a human receptionist.", name: "Kyle Newman", role: "Owner" },
    services: ["AI Receptionist", "Answering Service Replacement", "Cost Optimization", "Call Quality"],
    timeline: "7 days",
    heroStat: "$3K/Month Saved",
  },
  {
    title: "Commercial Plumber Never Misses a Dispatch Call",
    slug: "pacific-plumbing-dispatch-ai",
    client: "Pacific Plumbing Group",
    industry: "Commercial Plumbing",
    category: "ai-receptionist",
    featured: false,
    summary: "A commercial plumbing company's AI handles urgent dispatch calls 24/7, routing emergencies to on-call technicians instantly.",
    challenge: "Pacific Plumbing managed multiple commercial accounts that required 24/7 emergency response. Their on-call system relied on personal cell phones, leading to missed calls, delayed responses, and angry property managers threatening to switch providers.",
    solution: "We deployed an AI dispatch system that triages incoming calls, identifies true emergencies, and routes them directly to the on-call technician's phone. Non-emergencies are scheduled for the next business day. Every call is logged and transcribed.",
    results: "Emergency response time dropped from an average of 45 minutes to 5 minutes. Pacific retained all their at-risk commercial accounts and added 4 new ones. The AI handles an average of 35 after-hours calls per week.",
    metrics: [
      { label: "Emergency Response Time", before: "45 min", after: "5 min", improvement: "-89%" },
      { label: "Missed Emergency Calls", before: "8/mo", after: "0", suffix: "/mo", improvement: "-100%" },
      { label: "Client Retention", before: "82%", after: "100%", suffix: "%", improvement: "+22%" },
      { label: "New Contracts Won", before: "0", after: "4 (6 months)", improvement: "New" },
    ],
    testimonial: { quote: "Property managers used to complain about our response times. Now they're impressed that we answer in seconds and have a tech on-site in under an hour. The AI dispatch system saved our biggest accounts.", name: "Brian Pacific", role: "Operations Director" },
    services: ["AI Receptionist", "Emergency Dispatch", "Call Triage", "Commercial Account Management"],
    timeline: "14 days",
    heroStat: "5-Min Response Time",
  },
  {
    title: "HVAC Company Books 85% of AI-Answered Calls",
    slug: "smartair-solutions-ai-booking",
    client: "SmartAir Solutions",
    industry: "Residential HVAC",
    category: "ai-receptionist",
    featured: false,
    summary: "An AI receptionist books appointments directly into the calendar with an 85% conversion rate on answered calls.",
    challenge: "SmartAir's receptionist could only handle one call at a time. During peak seasons, 3-4 calls would come in simultaneously and callers got voicemail. Their booking rate on voicemail callbacks was only 25% — most customers had already called a competitor.",
    solution: "We implemented an AI receptionist that handles unlimited simultaneous calls. It accesses SmartAir's calendar in real-time, offers available appointment slots, and books directly — no callback needed. It also collects equipment information to prepare technicians.",
    results: "SmartAir now books 85% of all calls that the AI answers, up from 40% with their solo receptionist. They handle 3x more calls during peak periods and have eliminated the need for callbacks entirely.",
    metrics: [
      { label: "Call Booking Rate", before: "40%", after: "85%", suffix: "%", improvement: "+113%" },
      { label: "Simultaneous Call Capacity", before: "1", after: "Unlimited", improvement: "Unlimited" },
      { label: "Monthly Booked Appointments", before: "45", after: "95", suffix: "/mo", improvement: "+111%" },
      { label: "Callback Need", before: "60%", after: "0%", suffix: "%", improvement: "-100%" },
    ],
    testimonial: { quote: "The AI books more appointments than our human receptionist ever did. It never puts anyone on hold, never has a bad day, and books 85% of callers on the spot.", name: "Lisa Smart", role: "Owner" },
    services: ["AI Receptionist", "Calendar Integration", "Appointment Booking", "Peak Management"],
    timeline: "10 days",
    heroStat: "85% Booking Rate",
  },
  {
    title: "Plumber's AI Receptionist Qualifies Leads Automatically",
    slug: "horizon-plumbing-ai-qualification",
    client: "Horizon Plumbing",
    industry: "Residential Plumbing",
    category: "ai-receptionist",
    featured: false,
    summary: "An AI receptionist pre-qualifies every lead before a human ever touches it, saving 15 hours per week of staff time.",
    challenge: "Horizon Plumbing's office manager spent 3 hours daily on the phone qualifying leads — asking about the problem, location, budget, and timeline. Many calls turned out to be outside their service area or for services they didn't offer.",
    solution: "We trained the AI to ask qualifying questions naturally — service type, problem description, property location, and urgency level. It automatically filters out-of-area calls and non-service inquiries, passing only qualified leads to the team with full details.",
    results: "The office manager reclaimed 15 hours per week. Every lead that reaches the human team is pre-qualified and ready to schedule. Technician utilization improved because dispatchers have full job details before sending a crew.",
    metrics: [
      { label: "Weekly Staff Hours Saved", before: "0", after: "15 hrs", suffix: "/wk", improvement: "15 hrs saved" },
      { label: "Lead Qualification Rate", before: "55%", after: "92%", suffix: "%", improvement: "+67%" },
      { label: "Out-of-Area Calls Filtered", before: "0%", after: "100%", suffix: "%", improvement: "Automated" },
      { label: "Technician Utilization", before: "65%", after: "88%", suffix: "%", improvement: "+35%" },
    ],
    testimonial: { quote: "My office manager used to spend half her day on the phone qualifying leads. Now the AI does it better than we did. Every call that reaches us is a real opportunity.", name: "Nick Horizon", role: "Owner" },
    services: ["AI Receptionist", "Lead Qualification", "Call Routing", "CRM Integration"],
    timeline: "14 days",
    heroStat: "15 Hours/Week Saved",
  },
  {
    title: "HVAC Company Handles Spanish Calls with AI",
    slug: "coolbreeze-hvac-bilingual-ai",
    client: "CoolBreeze HVAC",
    industry: "Residential HVAC",
    category: "ai-receptionist",
    featured: false,
    summary: "A bilingual AI receptionist handles English and Spanish calls seamlessly, opening up a new 30% market segment.",
    challenge: "CoolBreeze served a community that was 30% Spanish-speaking, but they had no bilingual staff. Spanish-speaking callers would hang up when they couldn't communicate. They estimated losing 20+ potential customers per month to the language barrier.",
    solution: "We deployed a bilingual AI receptionist fluent in English and Spanish. It detects the caller's language automatically and responds naturally in either language. It handles booking, qualification, and FAQ responses in both languages.",
    results: "CoolBreeze captured 25 new Spanish-language leads per month — a market segment they'd been completely missing. Total lead volume increased by 35% and they hired a bilingual technician to serve the growing demand.",
    metrics: [
      { label: "Spanish-Language Leads", before: "0", after: "25", suffix: "/mo", improvement: "New" },
      { label: "Total Monthly Leads", before: "60", after: "81", suffix: "/mo", improvement: "+35%" },
      { label: "Spanish Market Capture", before: "0%", after: "30%", suffix: "%", improvement: "New" },
      { label: "Language-Related Hang-Ups", before: "20+/mo", after: "0", suffix: "/mo", improvement: "-100%" },
    ],
    testimonial: { quote: "We were losing a third of our potential market because of language. Now the AI handles Spanish calls beautifully. We've hired a bilingual tech just to keep up with the new demand.", name: "Miguel Breeze", role: "Owner" },
    services: ["Bilingual AI Receptionist", "Spanish Call Handling", "Market Expansion", "Lead Capture"],
    timeline: "10 days",
    heroStat: "35% More Leads",
  },
  {
    title: "Emergency Plumber Gets AI Triage for Urgent Calls",
    slug: "anchorpipe-emergency-ai-triage",
    client: "AnchorPipe Plumbing",
    industry: "Emergency Plumbing",
    category: "ai-receptionist",
    featured: false,
    summary: "An AI triage system separates true plumbing emergencies from routine calls, ensuring the fastest response for urgent issues.",
    challenge: "AnchorPipe's on-call plumber was getting woken up for non-emergencies — dripping faucets at midnight, running toilet questions at 3 AM. Real emergencies like burst pipes got the same response time as minor issues. Technician burnout was a serious problem.",
    solution: "We built an AI triage system that asks callers specific questions to assess urgency. True emergencies (flooding, gas leaks, sewage backups) get immediate dispatch. Non-emergencies are scheduled for the next business day with automated reminders.",
    results: "Unnecessary after-hours dispatches dropped by 70%. Technician burnout decreased dramatically. True emergency response times improved because on-call plumbers weren't exhausted from false alarms. Customer satisfaction increased because they got appropriate response times.",
    metrics: [
      { label: "False Emergency Dispatches", before: "18/mo", after: "5/mo", suffix: "/mo", improvement: "-72%" },
      { label: "True Emergency Response", before: "35 min", after: "12 min", improvement: "-66%" },
      { label: "Technician Burnout Rate", before: "High", after: "Low", improvement: "Resolved" },
      { label: "Customer Satisfaction", before: "3.8/5", after: "4.8/5", improvement: "+26%" },
    ],
    testimonial: { quote: "My plumbers aren't getting woken up for dripping faucets anymore. Real emergencies get faster response and everyone is happier — customers and employees alike.", name: "Dean Anchor", role: "Owner" },
    services: ["AI Receptionist", "Emergency Triage", "Smart Dispatch", "Call Prioritization"],
    timeline: "14 days",
    heroStat: "72% Fewer False Alarms",
  },
  {
    title: "HVAC Call Center Scales with AI During Peak Season",
    slug: "apex-climate-peak-ai",
    client: "Apex Climate Control",
    industry: "Commercial HVAC",
    category: "ai-receptionist",
    featured: false,
    summary: "An AI receptionist handles overflow calls during peak HVAC season, preventing the loss of high-value commercial leads.",
    challenge: "Apex Climate's 3-person phone team was overwhelmed during summer and winter peaks. Hold times exceeded 8 minutes and 35% of callers hung up. They considered hiring seasonal staff but training costs and turnover made it impractical.",
    solution: "We deployed AI as an overflow system that activates when all human agents are busy. The AI handles the same functions as human agents — booking, questions, and qualification. Callers experience zero hold time and seamless handoffs when agents become available.",
    results: "Abandoned calls dropped from 35% to 3%. Peak season lead capture improved by 45% without hiring additional staff. The AI handled an average of 120 overflow calls per month during peak periods.",
    metrics: [
      { label: "Call Abandonment Rate", before: "35%", after: "3%", suffix: "%", improvement: "-91%" },
      { label: "Peak Season Leads", before: "80/mo", after: "116/mo", suffix: "/mo", improvement: "+45%" },
      { label: "Average Hold Time", before: "8+ min", after: "0 sec", improvement: "-100%" },
      { label: "Seasonal Hiring Cost Saved", before: "$8K/season", after: "$0", improvement: "-100%" },
    ],
    testimonial: { quote: "We used to lose 35% of our peak season calls to hold times. Now every call gets answered instantly. The AI handles overflow so naturally that customers can't tell the difference.", name: "Ray Apex", role: "Call Center Manager" },
    services: ["AI Receptionist", "Overflow Management", "Peak Season Support", "Call Center Augmentation"],
    timeline: "14 days",
    heroStat: "91% Fewer Dropped Calls",
  },

  // ── Full-Service (8 projects) ──
  {
    title: "One-Man Plumber Grows to 8-Truck Fleet",
    slug: "premier-plumbing-full-service",
    client: "Premier Plumbing & Heating",
    industry: "Residential Plumbing",
    category: "full-service",
    featured: false,
    summary: "A solo plumber scaled to an 8-truck operation in 18 months with a complete digital marketing transformation.",
    challenge: "Joe ran Premier Plumbing alone with a flip phone and a truck. He had no website, no online presence, and survived entirely on word-of-mouth. He was turning away jobs he couldn't handle alone but had no way to attract enough business to justify hiring help.",
    solution: "We built everything from scratch — a professional website, Google Business Profile, Google Ads campaigns, local SEO, review generation, and an AI receptionist. We created a phased growth plan that added marketing channels as Joe hired and trained new plumbers.",
    results: "Premier Plumbing grew from 1 truck to 8 trucks in 18 months. Monthly revenue scaled from $15K to $145K. Joe now manages the business instead of running every call himself and has become the largest plumbing company in his county.",
    metrics: [
      { label: "Fleet Size", before: "1 truck", after: "8 trucks", improvement: "+700%" },
      { label: "Monthly Revenue", before: "$15K", after: "$145K", suffix: "/mo", improvement: "+867%" },
      { label: "Monthly Leads", before: "8", after: "120", suffix: "/mo", improvement: "+1400%" },
      { label: "Employees", before: "1 (owner)", after: "12", improvement: "+1100%" },
    ],
    testimonial: { quote: "I went from being a one-man band to running the biggest plumbing company in the county. LexumSoft didn't just get me leads — they helped me build a real business.", name: "Joe Premier", role: "Owner" },
    services: ["Website Design", "Google Ads", "SEO", "AI Receptionist", "Review Generation", "Growth Strategy"],
    timeline: "18 months",
    heroStat: "1 to 8 Trucks",
  },
  {
    title: "HVAC Company Doubles Revenue in Under a Year",
    slug: "total-comfort-hvac-full-service",
    client: "Total Comfort HVAC",
    industry: "Residential HVAC",
    category: "full-service",
    featured: false,
    summary: "A complete digital overhaul doubled this HVAC company's revenue from $600K to $1.2M in just 10 months.",
    challenge: "Total Comfort was stuck at $600K annual revenue for three straight years. They'd tried multiple marketing agencies with no improvement. Their website was outdated, they had no SEO presence, their ads were mismanaged, and they missed 30% of incoming calls.",
    solution: "We implemented a full-service package: new website, Google Ads rebuild, comprehensive SEO, review generation, and 24/7 AI receptionist. Every channel was integrated with unified tracking so we could see exactly what drove results and optimize accordingly.",
    results: "Total Comfort doubled from $600K to $1.2M in annual revenue within 10 months. They went from 30 leads per month to 95. Every marketing channel now contributes measurable ROI and they've achieved consistent month-over-month growth.",
    metrics: [
      { label: "Annual Revenue", before: "$600K", after: "$1.2M", improvement: "+100%" },
      { label: "Monthly Leads", before: "30", after: "95", suffix: "/mo", improvement: "+217%" },
      { label: "Marketing ROI", before: "1.5x", after: "6.8x", improvement: "+353%" },
      { label: "Call Answer Rate", before: "70%", after: "100%", suffix: "%", improvement: "+43%" },
    ],
    testimonial: { quote: "Three years of stagnation ended in 10 months. We doubled our revenue and finally feel like we're growing again. LexumSoft was the agency we'd been looking for all along.", name: "Tom Comfort", role: "Owner" },
    services: ["Website Redesign", "Google Ads", "SEO", "AI Receptionist", "Review Generation", "Analytics"],
    timeline: "10 months",
    heroStat: "Revenue Doubled",
  },
  {
    title: "Commercial Plumber Expands to 3 New Markets",
    slug: "diamond-plumbing-market-expansion",
    client: "Diamond Plumbing Co.",
    industry: "Commercial Plumbing",
    category: "full-service",
    featured: false,
    summary: "A commercial plumbing company used a full digital strategy to successfully expand into three new metropolitan markets.",
    challenge: "Diamond Plumbing dominated their home market but every expansion attempt failed. They'd open a new office, run some ads, and close it within a year. They had no strategy for building presence in a new market from zero.",
    solution: "We created a market expansion playbook — for each new city, we built location-specific landing pages, launched targeted Google Ads, built local citations, generated reviews from first customers, and deployed AI answering with local numbers.",
    results: "Diamond successfully expanded into three new metropolitan areas. Each new market reached profitability within 4 months. Combined revenue across all locations grew from $1.8M to $4.2M annually.",
    metrics: [
      { label: "Markets Served", before: "1", after: "4", improvement: "+300%" },
      { label: "Annual Revenue", before: "$1.8M", after: "$4.2M", improvement: "+133%" },
      { label: "Time to Profitability", before: "Never", after: "4 months", improvement: "Solved" },
      { label: "Total Monthly Leads", before: "45", after: "165", suffix: "/mo", improvement: "+267%" },
    ],
    testimonial: { quote: "We failed at expansion three times before LexumSoft. Their market entry playbook cracked the code. All three new markets are profitable and growing.", name: "Rick Diamond", role: "CEO" },
    services: ["Market Expansion", "Google Ads", "Local SEO", "Website Development", "AI Receptionist", "Review Generation"],
    timeline: "12 months",
    heroStat: "3 New Markets",
  },
  {
    title: "HVAC Startup Hits $1M Revenue in Year One",
    slug: "evercool-air-startup-growth",
    client: "EverCool Air Systems",
    industry: "Commercial HVAC",
    category: "full-service",
    featured: false,
    summary: "A brand-new HVAC company achieved $1M in revenue in its first year with a complete digital-first marketing strategy.",
    challenge: "EverCool was a startup with no reputation, no reviews, no online presence, and no existing customer base. The founder had 20 years of HVAC experience but zero marketing knowledge. He needed to build a business from absolute zero.",
    solution: "We built everything simultaneously — a professional website, aggressive Google Ads campaigns, Google Business Profile with review generation from day one, local SEO, social media presence, and AI receptionist. We ran introductory promotions to build the initial customer base.",
    results: "EverCool hit $1M in revenue in their first year of operation. They went from zero to 100+ Google reviews. They now employ 8 technicians and have become one of the fastest-growing HVAC companies in their state.",
    metrics: [
      { label: "First Year Revenue", before: "$0", after: "$1M", improvement: "From Zero" },
      { label: "Google Reviews (Year 1)", before: "0", after: "108", improvement: "108 Reviews" },
      { label: "Monthly Leads (Month 12)", before: "0", after: "85", suffix: "/mo", improvement: "From Zero" },
      { label: "Team Size (Year 1)", before: "1", after: "8 techs", improvement: "+700%" },
    ],
    testimonial: { quote: "I knew HVAC but I didn't know marketing. LexumSoft gave me the launch pad to build a million-dollar business in year one. I couldn't have done it without them.", name: "Darren Cool", role: "Founder" },
    services: ["Website Design", "Google Ads", "SEO", "Review Generation", "AI Receptionist", "Social Media", "Launch Strategy"],
    timeline: "12 months",
    heroStat: "$1M in Year One",
  },
  {
    title: "Family Plumber Modernizes After 30 Years",
    slug: "heritage-plumbing-modernization",
    client: "Heritage Plumbing",
    industry: "Residential Plumbing",
    category: "full-service",
    featured: false,
    summary: "A 30-year-old family plumbing business modernized its entire operation and reversed years of declining revenue.",
    challenge: "Heritage Plumbing had been in business for 30 years but revenue had declined for 5 straight years. The founder's son took over and realized they had no online presence, no modern marketing, and were losing customers to digitally savvy competitors.",
    solution: "We executed a complete digital transformation — new website preserving the company's heritage while looking modern, Google Ads targeting their legacy service area, local SEO recovery for lost rankings, review migration from old platforms, and AI receptionist.",
    results: "Heritage reversed their 5-year revenue decline in 6 months. They're now growing at 15% year-over-year. Their brand reputation has been revitalized, combining 30 years of trust with modern digital presence.",
    metrics: [
      { label: "Revenue Trend", before: "-8% YoY", after: "+15% YoY", improvement: "Reversed" },
      { label: "Monthly Leads", before: "18", after: "55", suffix: "/mo", improvement: "+206%" },
      { label: "Online Visibility", before: "Minimal", after: "Top 3 local", improvement: "Dominant" },
      { label: "Customer Avg Age", before: "55+", after: "35-65", improvement: "Expanded" },
    ],
    testimonial: { quote: "My dad built this business with handshakes. I almost lost it because I didn't adapt. LexumSoft helped me honor our heritage while competing in the modern world.", name: "Mike Heritage Jr.", role: "Owner" },
    services: ["Website Redesign", "Google Ads", "Local SEO", "Review Migration", "AI Receptionist", "Brand Refresh"],
    timeline: "6 months",
    heroStat: "Decline Reversed",
  },
  {
    title: "HVAC Company Becomes Regional Market Leader",
    slug: "climatefirst-hvac-market-leader",
    client: "ClimateFirst HVAC",
    industry: "Residential HVAC",
    category: "full-service",
    featured: false,
    summary: "An average-sized HVAC company used full-service digital marketing to become the dominant brand in a 5-county region.",
    challenge: "ClimateFirst was one of 40+ HVAC companies in their region with no differentiation. They had average reviews, average visibility, and average revenue. The owner wanted to become the undisputed #1 but didn't know how to break away from the pack.",
    solution: "We implemented an aggressive full-service strategy: premium website, dominant Google Ads presence, comprehensive SEO across 5 counties, 24/7 AI receptionist, and a brand authority campaign including sponsorships, content, and community engagement.",
    results: "ClimateFirst became the #1-ranked HVAC company in their 5-county region within 12 months. They captured 18% market share, up from 3%. Revenue grew from $800K to $2.4M and they added 10 employees.",
    metrics: [
      { label: "Regional Market Share", before: "3%", after: "18%", suffix: "%", improvement: "+500%" },
      { label: "Annual Revenue", before: "$800K", after: "$2.4M", improvement: "+200%" },
      { label: "Google Ranking (5 counties)", before: "Avg #8", after: "Avg #1", improvement: "#1 Average" },
      { label: "Monthly Leads", before: "25", after: "140", suffix: "/mo", improvement: "+460%" },
    ],
    testimonial: { quote: "We went from nobody to the #1 HVAC company in the region. People see our brand everywhere now. LexumSoft didn't just market us — they made us the market leader.", name: "Chad First", role: "Owner" },
    services: ["Website Design", "Google Ads", "Regional SEO", "AI Receptionist", "Brand Authority", "Content Marketing"],
    timeline: "12 months",
    heroStat: "#1 in 5 Counties",
  },
  {
    title: "Plumbing Company Achieves 10x Marketing ROI",
    slug: "titan-plumbing-10x-roi",
    client: "Titan Plumbing Solutions",
    industry: "Residential Plumbing",
    category: "full-service",
    featured: false,
    summary: "A plumbing company turned every marketing dollar into $10 of revenue with a fully integrated full-service approach.",
    challenge: "Titan Plumbing was spending $5,000/month across three different marketing vendors with no unified strategy. They had no idea which channels worked, duplicate efforts were wasting budget, and their total marketing ROI was a disappointing 1.8x.",
    solution: "We consolidated all marketing under one roof — website, ads, SEO, reviews, and AI receptionist — with unified tracking and attribution. We eliminated duplicate spend, reallocated budget to the highest-performing channels, and implemented end-to-end conversion tracking.",
    results: "Titan's marketing ROI jumped from 1.8x to 10.2x. They generate $51,000 in revenue from $5,000 in monthly marketing spend. Every channel is optimized and every dollar is tracked from click to completed job.",
    metrics: [
      { label: "Marketing ROI", before: "1.8x", after: "10.2x", improvement: "+467%" },
      { label: "Revenue from Marketing", before: "$9K/mo", after: "$51K/mo", suffix: "/mo", improvement: "+467%" },
      { label: "Marketing Spend", before: "$5K/mo (3 vendors)", after: "$5K/mo (unified)", improvement: "Same Budget" },
      { label: "Lead Attribution", before: "Unknown", after: "100% tracked", suffix: "%", improvement: "Full Visibility" },
    ],
    testimonial: { quote: "Same marketing budget, 10x the return. We were throwing money at three agencies with no coordination. LexumSoft unified everything and now we know exactly where every dollar goes.", name: "Tony Titan", role: "Owner" },
    services: ["Unified Marketing", "Google Ads", "SEO", "Website", "AI Receptionist", "Analytics Dashboard"],
    timeline: "6 months",
    heroStat: "10.2x ROI",
  },
  {
    title: "HVAC Company Builds Recurring Revenue Machine",
    slug: "allpro-heating-recurring-revenue",
    client: "AllPro Heating & Cooling",
    industry: "Residential HVAC",
    category: "full-service",
    featured: false,
    summary: "An HVAC company built a $500K recurring maintenance plan business on top of their existing service work.",
    challenge: "AllPro's revenue was entirely project-based — unpredictable and seasonal. They had zero recurring revenue and their pipeline went dry between peak seasons. The owner wanted stable, predictable income but didn't know how to market maintenance plans.",
    solution: "We built a comprehensive maintenance plan marketing system — a dedicated landing page with plan comparison, automated email campaigns to existing customers, Google Ads targeting maintenance keywords, and an AI receptionist trained to upsell plans on every service call.",
    results: "AllPro enrolled 450 maintenance plan members in 12 months, generating $500K in predictable annual recurring revenue. Maintenance customers also spend 3x more on upgrades and repairs, creating a powerful upsell engine.",
    metrics: [
      { label: "Maintenance Plan Members", before: "0", after: "450", improvement: "New Revenue Stream" },
      { label: "Annual Recurring Revenue", before: "$0", after: "$500K", improvement: "New" },
      { label: "Customer Lifetime Value", before: "$380", after: "$1,200", improvement: "+216%" },
      { label: "Revenue Predictability", before: "Seasonal", after: "60% recurring", improvement: "Stabilized" },
    ],
    testimonial: { quote: "Recurring revenue changed everything. I used to stress about finding the next job. Now I have $500K locked in before the year even starts. The maintenance plan marketing system is brilliant.", name: "Dave AllPro", role: "Owner" },
    services: ["Website Design", "Email Marketing", "Google Ads", "AI Receptionist", "Maintenance Plan Strategy", "CRM Setup"],
    timeline: "12 months",
    heroStat: "$500K Recurring Revenue",
  },
];

export function getFeaturedProjects(): Project[] {
  return PROJECTS.filter((p) => p.featured);
}

export function getProjectsByCategory(category: ProjectCategory): Project[] {
  return PROJECTS.filter((p) => p.category === category);
}

export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return PROJECTS.map((p) => p.slug);
}
